.eslintrc.js, .github/workflows/ci.yml, package-lock.json, package.json, src/aws-provider/aws-organization-reader.ts, src/aws-provider/aws-organization-writer.ts, src/aws-util.ts, src/build-tasks/build-configuration.ts, src/build-tasks/build-runner.ts, src/cfn-binder/cfn-template.ts, src/commands/base-command.ts, src/commands/create-organization-changeset.ts, src/commands/describe-stacks.ts, src/commands/init-organization-pipeline.ts, src/commands/init-organization.ts, src/commands/update-organization.ts, src/console-util.ts, src/core/generic-task-runner.ts, src/org-binder/org-tasks-provider.ts, src/parser/model/organization-section.ts, src/parser/model/password-policy-resource.ts, src/parser/model/resource.ts, src/parser/parser.ts, src/parser/validator.ts, src/resource-util.ts, src/state/storage-provider.ts, tsconfig.json
Linting is being added to the github actions and a few issues were fixed as well.
=> Support for linting in CI

docs/task-files.md
=> Fix logic in description of skip

docs/cli-reference.md
Minor doc fix so the runtime configuration table is formatted correctly in GitHub.
=> Fix table by removing extra column

.github/workflows/integration-test.yml, package.json, resources/delegated-build-orgformation-tasks.yml, src/build-tasks/build-configuration.ts, src/commands/perform-tasks.ts, src/parser/parser.ts, src/plugin/plugin-command.ts, src/util/aws-util.ts, src/util/child-process-util.ts, test/integration-tests/resources/scenario-delegated-build-account/0-update-organization.yml, test/integration-tests/resources/scenario-detached-perform-tasks/0-tasks.yml, test/integration-tests/resources/scenario-detached-perform-tasks/build-role.yml, test/integration-tests/resources/scenario-perform-tasks/organization.yml, test/unit-tests/commands/perform-tasks.test.ts, test/unit-tests/plugin/plugin-command.test.ts
fix: use default buildAccessRole on CDK and SLS closes #154
fix: tasks. allow update-rp in detached build
=> fix: use default buildAccessRole on CDK and SLS

src/commands/update-organization.ts
closes  #168, @eduardomourar could you confirm?
just published this under `0.9.15-beta.5`
=> fix: set update-org has ran flag also if no work has been done

package.json, src/commands/validate-stacks.ts, test/unit-tests/commands/validate-stacks.test.ts
cause it was broken. closes #173
=> fix validate stacks

package.json
=> feat: ofn alias

examples/readme.md
I guess without the configuration in the root account the example does not work.
=> add info about Billing Alerts

docs/access-denied.md
Hallo! As discussed on Slack - update to the access-denied pages to include non-default roles. Hopefully what I put makes sense - I'm still trying to work out how org-formation works! :-)
=> Updates details of non-default cross-account roles

docs/cli-reference.md, package.json, src/commands/update-stacks.ts, src/commands/validate-stacks.ts
=> feat: add organization-file to update/validate-stacks

CONTRIBUTING.md, README.md
Start a doc to provide info on how to start contributing to org-formation.
=> contributions doc

.github/ISSUE_TEMPLATE.md
A template for GH issues so that we get better info
=> GH issue template

README.md
@zaro0508 , what do you think?
=> doc: credits to khai

resources/orgformation-codepipeline.yml
*  Fixes https://github.com/org-formation/org-formation-cli/issues/207
* minor cfn-lint fixes
* Trigger pipeline using CloudWatch Event instead of CodePipeline polling
=> Fix #207 (repo branch master -> main)

src/commands/init-organization-pipeline.ts, src/commands/init-organization.ts, src/state/storage-provider.ts, src/util/aws-util.ts, test/integration-tests/resources/scenario-no-bucket/1-deploy-no-bucket.yml, test/integration-tests/resources/scenario-no-bucket/my-role.yml, test/integration-tests/resources/scenario-no-bucket/organization.yml, test/integration-tests/scenario-no-bucket.test.ts, test/unit-tests/commands/init-organization-pipeline.test.ts, test/unit-tests/commands/init-organization.test.ts
=> feat: use deafult region for bucket, create bucket if not existed

examples/templates/cloudtrail.yml
* Add S3 bucket deletion lifecycle policy and parameter
* Enable SSE on S3 bucket
* Enable block public access settings on S3 bucket
* Enforce HTTPS on S3 bucket policy
* Enable CloudTrail log file validation
=> Increase CloudTrail Example Security

src/commands/base-command.ts, src/commands/print-stacks.ts, src/commands/remove.ts, src/commands/update-stacks.ts, src/plugin/plugin-binder.ts, src/plugin/plugin-command.ts, test/integration-tests/scenario-update-stacks-with-param-expressions.test.ts
=> fix: Allow print tasks with FindInMap !CurrentAccount in parameters

examples/templating/organization-tasks.yaml
basically copied from example in the doc[1] since we know that
one works.
[1] https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#templating
=> Fix templating example

docs/task-files.md
provide example of using Mappings and !FindInMap
=> docs: add example

docs/articles/org-formation.md
=> docs: Fixed inline code command

docs/articles/aws-organizations.md
Just updating 'devide' to 'divide' in the documentation
=> docs: Update documentation

CHANGELOG.md, package.json, src/org-binder/org-tasks-provider.ts
closes https://github.com/org-formation/org-formation-cli/issues/385
=> Fix: no target id when attaching scp to root

src/cfn-binder/cfn-template.ts, src/parser/parser.ts, src/parser/validator.ts
closes https://github.com/org-formation/org-formation-cli/issues/392
=> feat: suport toplevel rules in template

CHANGELOG.md, package.json, src/org-binder/org-task-runner.ts
closes https://github.com/org-formation/org-formation-cli/issues/395
=> fix: update organization log output

CHANGELOG.md, package.json, src/aws-provider/aws-organization-reader.ts, src/plugin/impl/rp-build-task-plugin.ts, test/unit-tests/aws-provider/aws-organization-reader.organizational-units.test.ts
and fix: retry if type registration gets stuck
=> chore: better perf on update-organization

docs/organization-resources.md, src/aws-provider/aws-organization-writer.ts, src/org-binder/org-binder.ts, src/org-binder/org-tasks-provider.ts, src/parser/model/organization-root-resource.ts, test/unit-tests/aws-provider/aws-organization-writer.accounts.test.ts
=> feat: enable close account on removal

docs/articles/aws-organizations.md
=> Fix a typo

src/cfn-binder/cfn-task-provider.ts
closes https://github.com/org-formation/org-formation-cli/issues/459
=> fix: fail delete if termination protection is enabled

package-lock.json, src/util/aws-util.ts
Throws an error when encountering a ROLLBACK_FAILED instead of recreating the stack. Error message suggests manual action
=> fix: throw on ROLLBACK_FAILED instead of recreate stack

src/plugin/impl/cdk-build-task-plugin.ts
PR intends to fix https://github.com/org-formation/org-formation-cli/issues/480
For custom commands - new parameter is exposed, so that anybody can choose to change --output by themselves if needed
For default command, it changes behavior only when concurrency setting is added
This way current users are not impacted by this change and it is an optional improvement for those who choose to use it.
By setting cdk.out/{account} we isolate outputs of every process and prevent any locking that is happening
Example usage with custom command:
```
MaxConcurrentTasks: 100
CustomDeployCommand: !Sub 'npx cdk deploy --app "npx ts-node --prefer-ts-exts cdk/app.ts" --all ${CurrentTask.Parameters} --output cdk.out/${CurrentTask.AccountId}'
```
=> feat: remove cdk concurrency validation

docs/articles/org-formation.md
Update documentation with the current initial commit file structure.
=> Update initial commit file structure

cli-program.ts, docs/cli-reference.md, src/commands/create-organization-changeset.ts, src/commands/index.ts, src/commands/print-changeset.ts, test/unit-tests/commands/print-change-set.ts
The print-change-set function will output the changes a changeset will
perform, in either yaml or json.
=> Add print-change-set function to org-formation cli
