org-formation/org-formation-cli

docs/cloudformation-resources.md
docs/organization-resources.md
src/plugin/impl/cdk-build-task-plugin.ts
test/integration-tests/cdk-task.test.ts

This is a pull request for the issue discussed on [Slack](https://org-formation.slack.com/archives/CT6JQ05AA/p1595022047014600).
**Current behavior:**
At the moment the _update-cdk_ plugin sets the environment variables _CDK_DEFAULT_REGION_ and _CDK_DEFAULT_ACCOUNT_. However, the CDK CLI overwrites these variables using the same account/region resolution strategy as the AWS CLI. This means that the CDK workload cannot determine the correct region if the region is different from the region in which the org-formation tasks are executed. 
**Desired behavior:**
The CDK workload should be able to determine the correct region and account for deployment.
**Solution**
Add _CDK_DEPLOY_ACCOUNT_ and _CDK_DEPLOY_REGION_ to environment variables for _update-cdk_ tasks as suggested in the [AWS CDK …

Enable running 'update-cdk' tasks for multiple regions

---

.github/workflows/container.yaml
.gitignore
Dockerfile
README.md

This PR adds a GitHub action to build and push a container to hub.docker.com in response to a tag being pushed to this repo.
- Create an account if you don't have one already, e.g. `username`.
- Create a token.
- Create a repo, e.g. `org-formation-cli`
create the following secrets in this repo, `org-formation/org-formation-cli`:
- `DOCKER_USERNAME`, your username for hub.docker.com, e.g. `username`.
- `DOCKER_TOKEN`, the token associated with the username on hub.docker.com.
- `DOCKER_REPOSITORY`, the name of the user and repo on hub.docker.com, e.g. `username/org-formation-cli`
Once that's done, when you push a tag/RELEASE_VERSION to the repo, the GitHub action will do the following:
1. Login to hub.docker.com
2. Build a new container, passing the pushed tag/RELEASE_VERSION to the docker …

Add GitHub action to build and push a container to hub.docker.com

---

examples/templates/subdomains.yml

I was having a problem when running this example with multiple accounts with a subdomain. After investigation, I think we need to reference the hostedZone with `!GetAtt AWSAccount.Resources.HostedZone` in order to avoid this issue `validated failed. reason: Found multiple targets for reference to HostedZone`

Amend !Ref to HostedZone with AWSAccount.Resources

---

docs/cli-reference.md

In order to run the validate command, we need a few permissions. We will document them to help others users.
```json
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"s3:GetObject"
],
"Resource": "*",
"Effect": "Allow"
},
{
"Action": [
"cloudformation:GetExports",
"cloudformation:ListExports",
"cloudformation:ValidateTemplate"
],
"Resource": "*",
"Effect": "Allow"
},
{
"Action": [
"sts:AssumeRole"
],
"Resource": "arn:aws:iam::*:role/OrganizationAccountAccessRole",
"Effect": "Allow"
}
]
}
```

Add validate permission to CLI documentation

---

.github/workflows/container.yaml

Why:
* Builds were failing because set-env among others was deprecated in favour of redirecting to a new file: `$GITHUB_ENV`
* Added support for multi architecture build, adding arm64 for those on Apple M1.

Update github action for auto build on tag push

---

package-lock.json
package.json
src/util/aws-util.ts
test/unit-tests/util/aws-config-file
test/unit-tests/util/aws-shared-credentials-file
test/unit-tests/util/aws-util.test.ts

This will add support for credential process and AWS SSO within the AWS CLI config file as well as simplify the profile with MFA. ~~By leveraging a tool like [aws-sso-util](https://github.com/benkehoe/aws-sso-util), users can set AWS SSO even though the AWS SDK does not support it yet.~~ We are using a NPM library to load the AWS SSO configuration now.
Related to #123

Support credential process and SSO from AWS CLI config

---

src/build-tasks/build-configuration.ts
src/build-tasks/build-task-provider.ts
src/build-tasks/tasks/update-stacks-task.ts
src/cfn-binder/cfn-binder.ts
src/cfn-binder/cfn-task-provider.ts
src/commands/update-stacks.ts
src/commands/validate-stacks.ts
src/core/cfn-expression-resolver.ts
test/integration-tests/resources/scenario-cfn-parameter-expressions/1-deploy-update-stacks-with-param-expressions.yml
test/integration-tests/resources/scenario-cfn-parameter-expressions/bucket-policy.yml
test/integration-tests/scenario-update-stacks-with-param-expressions.test.ts
test/unit-tests/build-tasks/build-configuration.test.ts
test/unit-tests/build-tasks/build-task-provider.test.ts
test/unit-tests/templates/tasks.test.ts

allows for variations in template parameters based on !Ref CurrentAccount in a tasks file
e.g.
``` yml
Mappings:
MyMap:
IpAddresses:
112233112233: 10.201.30
112233112234: 10.201.31
MyStack:
Type: update-stacks
Template: ./template.yml
StackName: just-an-example
Parameters:
ip: !FindInMap [MyMap, IpAddresses, !Ref CurrentAccount]
```
closes  #206

support using !FindInMap together with !Ref CurrentAccount

---

examples/templates/budget-alarms.yml

Changing this to 90% as 1% seems incorrect. Changing this also requires all budgets are manually deleted as per https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/365 so a more sensible doc default seems like a good idea.

Docs Template - Increase Budget Threshold to 90%

---

docs/cli-reference.md

Fixes `ERROR: argument --stack-name is missing`

Fix delete-stack CLI Docs

---

package-lock.json
package.json
src/util/aws-util.ts

A new version of the `aws-sdk-sso` library has been released to NPM, so we can use that instead.

Use AWS SSO provider from NPM

---

Dockerfile

I noticed that the `build-arg` for `RELEASE_VERSION` in the github action was not behaving as expected in a different but similar repo.  The same issue is present here.  This PR fixes the issue.

The ARG command should be after FROM command

---

src/plugin/impl/rp-build-task-plugin.ts

related to #233. i think the direction should be to point people in the direction of AWS provided CFN types for registration. the registr-type action was a temporary solution in absence of AWS native support.

fix: clarify workaround custom rps

---

src/commands/init-organization-pipeline.ts
test/unit-tests/commands/init-organization-pipeline.test.ts

fix for https://github.com/org-formation/org-formation-cli/issues/247

fix: missing role in build account when running init-pipeline

---

src/build-tasks/build-configuration.ts
src/commands/base-command.ts
src/util/aws-util.ts
test/integration-tests/resources/scenario-task-file-parameters/1-task-file-with-parameters.yml
test/integration-tests/resources/scenario-task-file-parameters/included-task-file-with-pseudo-param.yml
test/integration-tests/scenario-task-file-parameters.test.ts

adds support for pseudo parameter "AWS::Partition" to task files.
example 
``` yaml
Mappings:
Partition:
BindingRegions:
aws: eu-west-1
aws-us-gov: us-gov-west-1
BucketTemplate:
Type: update-stacks
Template: ./bucket.yml
StackName: !Sub ${stackPrefix}-scenario-stack-parameters
DefaultOrganizationBindingRegion: !FindInMap [ Partition, BindingRegions, !Ref AWS::Partition ]
DefaultOrganizationBinding:
IncludeMasterAccount: true
```

feat: partition pseudo parameter in tasks

---

src/writer/default-template-writer.ts

An account tag with a value that includes a colon followed by a space breaks the yaml parser.
Correctly quote these values on generation.

Tag values with ': ' break the yaml writer

---

src/parser/validator.ts

When `binding.ExcludeOrganizationalUnit` exists, `binding.OrganizationalUnit` was incorrectly being passed to `Validator.validateReferenceToOU()` in its place.
This typo can cause either:
1. an invalid `ExcludeOrganizationalUnit` to slip by, or
2. an unintended error when a valid `ExcludeOrganizationalUnit` binding exists alone without a valid `OrganizationalUnit` binding.

fix: ExcludeOrganizationalUnit is not validated

---

src/util/aws-util.ts
test/integration-tests/tools/test-cfn-exports-backoff.ts

might be on the defensive side, but undefined values will not be cached
closes: https://github.com/org-formation/org-formation-cli/issues/302

feat: cache reading cfn exports and retry when throttled

---

cli-program.ts
src/build-tasks/tasks/organization-task.ts
src/commands/index.ts
src/commands/print-org.ts
src/commands/update-organization.ts
src/commands/validate-organization.ts
test/unit-tests/commands/print-org.test.ts

Fixed typo which prevented organization file from using templateContext reported by me: #339 
Also added a `print-org` command, which just generates the organization template and outputs to console as either yaml or json so I can develop a good nunjucks template without using the `update` command. Added a simple print-org test as well.

fix org file templating, add print-org command

---

src/commands/print-stacks.ts

print-tasks and print-stacks will resolve references (e.g. CopyValue statements) reaching out to AWS CloudFormation. We like to split the roles used for that between read-only tasks like printing and doing perform-tasks which requires a lot of privilege. This change will have print-tasks and print-stacks observe the TaskRoleName parameter on the task

fix: use TaskRoleName when printing tasks

---

src/aws-provider/aws-organization-writer.ts

fix issue where PartitionAccountId and AccountId is required in organization file or it tries to recreate the partition and fails due to EMAIL_ALREADY_EXISTS error

fix email already exists error on partition accounts

---

docs/cloudformation-resources.md
src/build-tasks/tasks/update-stacks-task.ts
src/cfn-binder/cfn-binder.ts
src/cfn-binder/cfn-template.ts
test/resources/enum-expressions/enum-expressions.yml
test/resources/enum-expressions/organization.yml
test/unit-tests/templates/enum-expressions.test.ts

COMPLETED:
- make `Fn::EnumTargetAccounts` more useful in CloudFormation Templates
- Add AccountId parameter
- Add LogicalId parameter
- Add AccountName parameter
- Add Alias parameter
- Add RootEmail parameter
- Add Tags parameter (the value here will be replaced if it matches a Tag Key on the account)
- resolve `Fn::EnumTargetAccounts` in TemplatingContext on stack-updates tasks
- Add new tests
- Fix old tests
- Test Partition
- Update documentation
-------------------------------
Updates to CloudFormation Template Expression Resolving
```yaml
EnumAccountsExpression:
Type: Custom::EnumAccountsExpressionTest
Properties:
accounts: Fn::EnumTargetAccounts AllAccountsBinding ${account} # backwards compatibility
AccountIds: Fn::EnumTargetAccounts AllAccountsBinding ${AccountId}
LogicalIds: …
```

make Fn::EnumTargetAccounts more useful

---

docs/cli-reference.md
src/core/cfn-parameters.ts
test/unit-tests/core/cfn-parameters.test.ts

With the AWS CLI, it is possible to provide comma-delimited parameter values to `cloudformation update-stack`/`create-stack` using either of the following formats:
1. `--parameters ParameterKey=foo,ParameterValue=one\,two`
2. `--parameters ParameterKey=foo,ParameterValue="one,two"`
The current org-formation parser splits on commas and discards the `two` part above as a result.
I was attempting to use this syntax in the `update-stacks` command to pass the supported AWS regions as a [`CommaDelimitedList`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) property, i.e., `--parameters ParameterKey=SupportedRegions,ParameterValue=eu-west-1\,eu-west-2\,eu-central-1` but observed that only the first region was being passed and included the …

Support comma-delimited CloudFormation parameter values

---

CHANGELOG.md
package.json
src/commands/validate-organization.ts

currently, when an SCP or OU is added in the organization.yml file printing and validation is skipped. this however does only make sense if an account is added.

fix: ensure printing and validation only skipped when accounts are added

---

src/aws-provider/aws-organization-writer.ts

This change ensures that there is no DeletAccountPasswordPolicy prior to updating the password policy.

fix: ensure pwd policy does not get deleted prior to update

---

CHANGELOG.md
docs/cli-reference.md
package.json
src/commands/perform-tasks.ts
test/unit-tests/commands/perform-tasks.test.ts

When executing the `perform-tasks` command it is possible to use the optional flag `--task-matcher` to specify a glob pattern. The glob pattern is used to filter and skip all of the non-matching tasks.
It works by composing a `fullTaskName` based on the `task.name` and its `parentTask.name`. The obtained `fullTaskName` is then matched against the provided glob pattern to decide if the task should be skipped or not (this is done only for the leaf tasks). Any non-matching `fullTaskName` will be skipped from execution.
* If a `parentTask` has all of its `childTasks` skipped then the `parentTask` is also skipped
* this flag gives priority to the `skip` property of a task. If a task has the `skip` property set to `true` then even if the task matches the glob pattern it will still be skipped. …

Task matchers

---

src/yaml-cfn/index.ts

Adds the new tags that can be found in the `AWS::LanguageExtensions` transform:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html

fix: adds missing language extensions yaml tags

---

docs/task-files.md

Current implementation does not automatically install Terraform, added a note to inform users of this.
Natively Terraform does not really offer a multi-platform installation method, like ie. CDK does via NPM, so it seems a good idea to have the user install their required TF version themselves.

Chore:tf docs

---

resources/orgformation-codepipeline.yml

AWS has announced the deprecation of codebuild standard image version 4. This sets the version to 6 for new users of org-formation pipeline. 
Deprecation will start march 31, 2023. If you're using a version 4 image, you should have gotten an email from AWS.
I've tested this by updating the image to v6 in an existing deployment.
AWS's message:
```
Hello,
We are reaching out to you because you ran a build using the Ubuntu standard 4.0 [1] Docker Image, in the last 30 days.
Starting March 30, 2023, AWS CodeBuild will be moving these images to an unsupported status and they will not be cached on the build hosts anymore.
You may continue using these images for your builds, but will notice an increase in provisioning latency after March 30, 2023.
These images will also not be getting any new …
```

update to codebuild standard 6

---

CHANGELOG.md
src/build-tasks/tasks/update-stacks-task.ts

fix: ensure the delete stacks command falls back to concurrency settings of the perform-task operation

fix: ensure the delete stacks command falls back to concurrency settings

---

src/aws-provider/aws-organization-writer.ts

This will allow for the maximum characters 5120 to be used without whitespace counting towards that total. AWS will store the policy in the minified state but render it in the console with pretty print.

Format SCP without indentation reducing policy size

---

Dockerfile

closes https://github.com/org-formation/org-formation-cli/issues/544

chore: update docker to node18

---

src/commands/print-changeset.ts

Throwing an exception correctly sets the exit code to 1 when the change set is not found.

Add exception to print-change-set if not found

---

src/commands/base-command.ts
src/commands/init-organization-pipeline.ts
src/state/storage-provider.ts
src/util/aws-util.ts

Resolves issue where state bucket was being created in management account when using build account.  This appeared to be a regression from the v3 AWS cli update change.
Fixes: #548

fix: access denied error when using build-account-id for init-pipeline

---

src/util/aws-util.ts

Fixes org-formation/org-formation-cli#569
A new `S3Client` needs to be constructed whenever the template is uploaded to a new region. This isn't currently happening because `region` is not being passed as an argument to `GetCredentialProviderWithRoleAssumptions` when building the `cacheKey` within the `GetS3Service` function. This results in `GetS3Service` not seeing the request as a new `cacheKey` and the first `S3Client` is reused when it should not be.

fix: Perform-tasks fails when creating/updating stacks with large templates to 2+ regions #569

---

README.md

The README is a suitable place to document an important (non-obvious) aspect of improving parallelism.
Resolves #524

docs: highlight MaxConcurrentTasks on include tasks

---

src/commands/create-organization-changeset.ts
src/commands/print-stacks.ts
src/commands/update-stacks.ts
test/unit-tests/plugin/impl/cdk-build-task-plugin.test.ts
test/unit-tests/plugin/impl/sls-build-task-plugin.test.ts

Resolves [this](https://github.com/org-formation/org-formation-cli/issues/599) issue for CreateChangeSetCommand!
Want to let this flow throw the integration tests, will look at updating PrintStackCommand as well

Pass TemplateContext to CreateChangeSetCommand
